AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: HelloWorldLambdaJava

Resources:
  HelloWorldLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloWorldJavaGB
      Runtime: java8
      MemorySize: 512
      Timeout: 2
      Handler: book.EnvVarLambda::handler
      CodeUri: target/HelloWorldLambdaJava-1.0-SNAPSHOT.jar
      Environment:
        Variables:
          DATABASE_URL: my-database-url